### ISSUE TITLE
qeds in Colab: RecursionError: maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by pjakobsen** [QuantEcon/quantecon-notebooks-datascience#6]
After installation  with recommend `! pip install qeds`  in Google Colab (Python3), I get some strange recursion errors, always variation on the same theme:  

```
import qeds
qeds.themes.mpl_style();

---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-16-72b73e412c56> in <module>()
      5 # activate plot theme
      6 import qeds
----> 7 qeds.themes.mpl_style();

1 frames
/usr/local/lib/python3.6/dist-packages/qeds/themes.py in mpl_style()
     49     rcp['axes.labelsize'] = 'large'
     50 
---> 51     plt.style.library["qeds"] = mpl_style()
     52     plt.style.reload_library()
     53     plt.style.use("qeds")

... last 1 frames repeated, from the frame below ...

/usr/local/lib/python3.6/dist-packages/qeds/themes.py in mpl_style()
     49     rcp['axes.labelsize'] = 'large'
     50 
---> 51     plt.style.library["qeds"] = mpl_style()
     52     plt.style.reload_library()
     53     plt.style.use("qeds")

RecursionError: maximum recursion depth exceeded in comparison


```

**Comment by pjakobsen** [comment]
Running this works like a charm:


```
import qeds
qeds.data.available()

#qeds.themes.mpl_style();

--------------------------------------------------
['test',
 'state_fips',
 'state_employment',
 'state_industry_employment',
 'goodreads_books',
 'goodreads_ratings',
 'goodreads_tags',
 'goodreads_book_tags',
 'airline_performance_dec16',
 'airline_performance_nov16',
 'airline_carrier_codes',
 'nyc_employee',
 'chipotle_raw']
```

**Comment by jlperla** [comment]
Thanks for the report.  @wupeifan  aer you seeing the same thing?  Any ideas @sglyon  @cc7768  ?

**Comment by wupeifan** [comment]
Yeah, I can confirm this issue. And it is not the only issue: `qeds.themes.plotly_template()` also triggers a similar error.
This never happened when we soft-launched. Maybe @sglyon changed something in the latest version of qeds, or there are some package updates that we are not aware of...

**Comment by sglyon** [comment]
Thanks for reporting @pjakobsen 

I didn't change anything. Not sure what if anything might have changed from underneath us

**Comment by jlperla** [comment]
Do we know if this colab only? Haven't seen it with normal builds. Did a backend dependency change on the baseline colab images,and how might we check?

**Comment by wupeifan** [comment]
Things are well on pims or ubc.syzygy, so I think it is Colab only. If Spencer didn't change anything in qeds (rather just an update in version number) then it could be some dependent packages that have changed I guess...

**Comment by wupeifan** [comment]
fixed by https://github.com/QuantEcon/qeds/issues/3
