### ISSUE TITLE
Potential Inaccuracy in `quantecon-notebooks-datascience/python_fundamentals/control_flow.ipynb`

### ISSUE THREAD

**Issue by tiagobotelh0** [QuantEcon/quantecon-notebooks-datascience#7]
Lines 179-181 in the source blob of `quantecon-notebooks-datascience/python_fundamentals/control_flow.ipynb` read:

>  "Note that we can also consider an asset that lives and pays forever if\n",
    "$ T= \\infty $, and from [(2)](#equation-eq-infinite-sums), the value of an asset which\n",
    "pays 1 forever is $ \\frac{r}{1+r} $."

when in fact the infinite series associated with an asset that pays 1 forever converges to $ \\frac{1+r}{r} > 1$, assuming $ r \geq 0 $. 

Am I missing something? If not, I kindly request that someone fix this issue.

**Comment by wupeifan** [comment]
Yeah, that's a typo. Thanks for pointing it out.

**Comment by wupeifan** [comment]
updated, FYI

**Comment by tiagobotelh0** [comment]
@wupeifan thanks for the update!

While we're at it, there seems to be another typo in that same notebook: lines 407-408 in the source blob read:

> "In this case, because the conditional for the `if` statement was not\n",
   "`True`, the if code block was not executed, but the `else` block was.\n",

but note that the 'if' conditional (`val is False`) must be `True`, since we have defined `val` to be the boolean `2 == 4`. Indeed, when the code is run, its output prints the 'if' code block, but _not_ the 'else' code block.

**Comment by wupeifan** [comment]
good catch. are there any more of those? so i don't have to update every time. thanks

**Comment by tiagobotelh0** [comment]
There are a couple of other corrections to be made in this particular section.

1. In Exercise 5, the markdown cell says `r = 0.05` and `w_hs = 40_000`, but the code cell says `r = 1.05` and `w_hs = 35_000`. While the discount rate in the code seems to be a typo, the choice of `w_hs` is more subtle: I solved for both values, and `w_hs = 40_000` would imply that the student _shouldn't_ enroll in college, whereas `w_hs = 35_000` would imply that they should.

2. It's not clear what exactly is meant by `x` in Exercises 8 and 9, since no array-like object with that name was defined in this lecture.

For now, those are all of my suggestions, though I have yet to read the other lectures in the next few days. Is it OK if I open another issue or point out more typos (if any exist) in the other lectures as well?

**Comment by wupeifan** [comment]
I think I fixed those two things in an earlier version. It must be I overrode some of them by accident.
Thanks for pointing out these typos.
